(module
  (type $st0 (sub (struct (field i32))))
  (type $st1 (sub $st0 (struct (field i32 i32))))
  (type $st2 (struct (field i64)))
  (type $ar0 (sub (array i32)))
  (type $ar1 (sub $ar0 (array i32)))
  (type $ar2 (array i64))

  (table $t_any 7 (ref any) (ref.i31 (i32.const 0)))
  (table $tn_any 8 (ref null any))
  (table $t_struct 3 (ref struct) (struct.new_default $st0))
  (table $tn_struct 4 (ref null struct))
  (table $t_array 3 (ref array) (array.new_default $ar0 (i32.const 1)))
  (table $tn_array 4 (ref null array))

  (func (export "init")
    (table.set $t_any (i32.const 0) (ref.i31 (i32.const 1)))
    (table.set $t_any (i32.const 1) (struct.new_default $st0))
    (table.set $t_any (i32.const 2) (struct.new_default $st1))
    (table.set $t_any (i32.const 3) (struct.new_default $st2))
    (table.set $t_any (i32.const 4) (array.new_default $ar0 (i32.const 1)))
    (table.set $t_any (i32.const 5) (array.new_default $ar1 (i32.const 1)))
    (table.set $t_any (i32.const 6) (array.new_default $ar2 (i32.const 1)))

    (table.set $tn_any (i32.const 0) (ref.null any))
    (table.set $tn_any (i32.const 1) (ref.i31 (i32.const 1)))
    (table.set $tn_any (i32.const 2) (struct.new_default $st0))
    (table.set $tn_any (i32.const 3) (struct.new_default $st1))
    (table.set $tn_any (i32.const 4) (struct.new_default $st2))
    (table.set $tn_any (i32.const 5) (array.new_default $ar0 (i32.const 1)))
    (table.set $tn_any (i32.const 6) (array.new_default $ar1 (i32.const 1)))
    (table.set $tn_any (i32.const 7) (array.new_default $ar2 (i32.const 1)))

    ;; $t_struct[0] is (struct.new_default $st0)
    (table.set $t_struct (i32.const 1) (struct.new_default $st1))
    (table.set $t_struct (i32.const 2) (struct.new_default $st2))

    ;; $tn_struct[0] is ref.null
    (table.set $tn_struct (i32.const 1) (struct.new_default $st0))
    (table.set $tn_struct (i32.const 2) (struct.new_default $st1))
    (table.set $tn_struct (i32.const 3) (struct.new_default $st2))

    ;; $t_array[0] is (array.new_default $ar0 (i32.const 1))
    (table.set $t_array (i32.const 1) (array.new_default $ar1 (i32.const 1)))
    (table.set $t_array (i32.const 2) (array.new_default $ar2 (i32.const 1)))

    ;; $tn_array[0] is ref.null
    (table.set $tn_array (i32.const 1) (array.new_default $ar0 (i32.const 1)))
    (table.set $tn_array (i32.const 2) (array.new_default $ar1 (i32.const 1)))
    (table.set $tn_array (i32.const 3) (array.new_default $ar2 (i32.const 1)))
  )

  (func (export "t_any1") (result i32 i32 i32 i32 i32)
    (ref.test (ref $st0) (table.get $t_any (i32.const 0)))
    (ref.test (ref null $st0) (table.get $t_any (i32.const 1)))
    (ref.test (ref $st0) (table.get $t_any (i32.const 2)))
    (ref.test (ref null $st0) (table.get $t_any (i32.const 3)))
    (ref.test (ref $st0) (table.get $t_any (i32.const 4)))
    (ref.cast (ref $st0) (table.get $t_any (i32.const 1))) (drop)
    (ref.cast (ref null $st0) (table.get $t_any (i32.const 2))) (drop)
  )

  (func (export "t_any2") (result i32 i32 i32 i32 i32)
    (ref.test (ref $st1) (table.get $t_any (i32.const 0)))
    (ref.test (ref null $st1) (table.get $t_any (i32.const 1)))
    (ref.test (ref $st1) (table.get $t_any (i32.const 2)))
    (ref.test (ref null $st1) (table.get $t_any (i32.const 3)))
    (ref.test (ref $st1) (table.get $t_any (i32.const 4)))
    (ref.cast (ref null $st1) (table.get $t_any (i32.const 2))) (drop)
  )

  (func (export "t_any3") (result i32 i32 i32 i32 i32)
    (ref.test (ref $st2) (table.get $t_any (i32.const 0)))
    (ref.test (ref null $st2) (table.get $t_any (i32.const 1)))
    (ref.test (ref $st2) (table.get $t_any (i32.const 2)))
    (ref.test (ref null $st2) (table.get $t_any (i32.const 3)))
    (ref.test (ref $st2) (table.get $t_any (i32.const 4)))
    (ref.cast (ref null $st2) (table.get $t_any (i32.const 3))) (drop)
  )

  (func (export "t_any4") (result i32 i32 i32 i32 i32)
    (ref.test (ref $ar0) (table.get $t_any (i32.const 0)))
    (ref.test (ref null $ar0) (table.get $t_any (i32.const 1)))
    (ref.test (ref $ar0) (table.get $t_any (i32.const 4)))
    (ref.test (ref null $ar0) (table.get $t_any (i32.const 5)))
    (ref.test (ref $ar0) (table.get $t_any (i32.const 6)))
    (ref.cast (ref $ar0) (table.get $t_any (i32.const 4))) (drop)
    (ref.cast (ref null $ar0) (table.get $t_any (i32.const 5))) (drop)
  )

  (func (export "t_any5") (result i32 i32 i32 i32 i32)
    (ref.test (ref $ar1) (table.get $t_any (i32.const 0)))
    (ref.test (ref null $ar1) (table.get $t_any (i32.const 1)))
    (ref.test (ref $ar1) (table.get $t_any (i32.const 4)))
    (ref.test (ref null $ar1) (table.get $t_any (i32.const 5)))
    (ref.test (ref $ar1) (table.get $t_any (i32.const 6)))
    (ref.cast (ref null $ar1) (table.get $t_any (i32.const 5))) (drop)
  )

  (func (export "t_any6") (result i32 i32 i32 i32 i32)
    (ref.test (ref $ar2) (table.get $t_any (i32.const 0)))
    (ref.test (ref null $ar2) (table.get $t_any (i32.const 1)))
    (ref.test (ref $ar2) (table.get $t_any (i32.const 4)))
    (ref.test (ref null $ar2) (table.get $t_any (i32.const 5)))
    (ref.test (ref $ar2) (table.get $t_any (i32.const 6)))
    (ref.cast (ref null $ar2) (table.get $t_any (i32.const 6))) (drop)
  )

  (func (export "t_any7")
    (ref.cast (ref null $st0) (table.get $t_any (i32.const 0))) (drop)
  )

  (func (export "t_any8")
    (ref.cast (ref null $ar0) (table.get $t_any (i32.const 1))) (drop)
  )

  (func (export "t_any9") (result i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref $st0) (table.get $t_any (i32.const 0))) (i32.const 6) (br 1))
        (drop) (i32.const 10))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null $st0) (table.get $t_any (i32.const 2))) (i32.const 7) (br 1))
        (drop) (i32.const 11))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref $ar0) (table.get $t_any (i32.const 5))) (i32.const 8) (br 1))
        (drop) (i32.const 12))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null $ar1) (table.get $t_any (i32.const 5))) (i32.const 9) (br 1))
        (drop) (i32.const 13))
  )

  (func (export "tn_any1") (result i32 i32 i32 i32 i32 i32)
    (ref.test (ref null $st0) (table.get $tn_any (i32.const 0)))
    (ref.test (ref null $st1) (table.get $tn_any (i32.const 0)))
    (ref.test (ref null $st2) (table.get $tn_any (i32.const 0)))
    (ref.test (ref null $ar0) (table.get $tn_any (i32.const 0)))
    (ref.test (ref null $ar1) (table.get $tn_any (i32.const 0)))
    (ref.test (ref null $ar2) (table.get $tn_any (i32.const 0)))
    (ref.cast (ref null $st0) (table.get $tn_any (i32.const 0))) (drop)
    (ref.cast (ref null $st1) (table.get $tn_any (i32.const 0))) (drop)
    (ref.cast (ref null $st2) (table.get $tn_any (i32.const 0))) (drop)
    (ref.cast (ref null $ar0) (table.get $tn_any (i32.const 0))) (drop)
    (ref.cast (ref null $ar1) (table.get $tn_any (i32.const 0))) (drop)
    (ref.cast (ref null $ar2) (table.get $tn_any (i32.const 0))) (drop)
  )

  (func (export "tn_any2") (result i32 i32 i32 i32 i32)
    (ref.test (ref null $st0) (table.get $tn_any (i32.const 1)))
    (ref.test (ref $ar2) (table.get $tn_any (i32.const 1)))
    (ref.test (ref $st0) (table.get $tn_any (i32.const 2)))
    (ref.test (ref null $ar2) (table.get $tn_any (i32.const 6)))
    (ref.test (ref $ar2) (table.get $tn_any (i32.const 7)))
    (ref.cast (ref $st0) (table.get $tn_any (i32.const 2))) (drop)
    (ref.cast (ref null $st0) (table.get $tn_any (i32.const 3))) (drop)
    (ref.cast (ref $ar0) (table.get $tn_any (i32.const 5))) (drop)
    (ref.cast (ref null $ar0) (table.get $tn_any (i32.const 6))) (drop)
  )

  (func (export "tn_any3")
    (ref.cast (ref $st0) (table.get $tn_any (i32.const 0))) (drop)
  )

  (func (export "tn_any4")
    (ref.cast (ref null $ar0) (table.get $tn_any (i32.const 1))) (drop)
  )

  (func (export "tn_any5")
    (ref.cast (ref $ar0) (table.get $tn_any (i32.const 7))) (drop)
  )

  (func (export "tn_any6") (result i32 i32 i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref $st0) (table.get $tn_any (i32.const 0))) (i32.const 2) (br 1))
        (drop) (i32.const 8))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref $st0) (table.get $tn_any (i32.const 0))) (i32.const 3) (br 1))
        (drop) (i32.const 9))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null $ar1) (table.get $tn_any (i32.const 0))) (i32.const 4) (br 1))
        (drop) (i32.const 10))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null $ar1) (table.get $tn_any (i32.const 0))) (i32.const 5) (br 1))
        (drop) (i32.const 11))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null $ar2) (table.get $tn_any (i32.const 1))) (i32.const 6) (br 1))
        (drop) (i32.const 12))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null $ar2) (table.get $tn_any (i32.const 1))) (i32.const 7) (br 1))
        (drop) (i32.const 13))
  )

  (func (export "tn_any7") (result i32 i32 i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null $st0) (table.get $tn_any (i32.const 2))) (i32.const 9) (br 1))
        (drop) (i32.const 15))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null $st0) (table.get $tn_any (i32.const 2))) (i32.const 10) (br 1))
        (drop) (i32.const 16))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref $st0) (table.get $tn_any (i32.const 3))) (i32.const 11) (br 1))
        (drop) (i32.const 17))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref $st0) (table.get $tn_any (i32.const 3))) (i32.const 12) (br 1))
        (drop) (i32.const 18))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null $ar1) (table.get $tn_any (i32.const 7))) (i32.const 13) (br 1))
        (drop) (i32.const 19))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null $ar1) (table.get $tn_any (i32.const 7))) (i32.const 14) (br 1))
        (drop) (i32.const 20))
  )

  (func (export "t_struct1") (result i32 i32 i32 i32 i32 i32)
    (ref.test (ref null $st0) (table.get $t_struct (i32.const 0)))
    (ref.test (ref $st0) (table.get $t_struct (i32.const 1)))
    (ref.test (ref null $st0) (table.get $t_struct (i32.const 2)))
    (ref.test (ref $st1) (table.get $t_struct (i32.const 0)))
    (ref.test (ref null $st1) (table.get $t_struct (i32.const 1)))
    (ref.test (ref $ar0) (table.get $t_struct (i32.const 0)))
    (ref.cast (ref $st0) (table.get $t_struct (i32.const 0))) (drop)
    (ref.cast (ref null $st0) (table.get $t_struct (i32.const 1))) (drop)
    (ref.cast (ref $st1) (table.get $t_struct (i32.const 1))) (drop)
    (ref.cast (ref null $st2) (table.get $t_struct (i32.const 2))) (drop)
  )

  (func (export "t_struct2")
    (ref.cast (ref $st0) (table.get $t_struct (i32.const 2))) (drop)
  )

  (func (export "t_struct3")
    (ref.cast (ref null $ar0) (table.get $t_struct (i32.const 0))) (drop)
  )

  (func (export "t_struct4") (result i32 i32 i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null $st0) (table.get $t_struct (i32.const 0))) (i32.const 6) (br 1))
        (drop) (i32.const 12))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null $st0) (table.get $t_struct (i32.const 0))) (i32.const 7) (br 1))
        (drop) (i32.const 13))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref $st0) (table.get $t_struct (i32.const 1))) (i32.const 8) (br 1))
        (drop) (i32.const 14))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref $st0) (table.get $t_struct (i32.const 1))) (i32.const 9) (br 1))
        (drop) (i32.const 15))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null $ar0) (table.get $t_struct (i32.const 2))) (i32.const 10) (br 1))
        (drop) (i32.const 16))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null $ar0) (table.get $t_struct (i32.const 2))) (i32.const 11) (br 1))
        (drop) (i32.const 17))
  )

  (func (export "tn_struct1") (result i32 i32 i32 i32 i32 i32)
    (ref.test (ref null $st0) (table.get $tn_struct (i32.const 0)))
    (ref.test (ref null $st1) (table.get $tn_struct (i32.const 0)))
    (ref.test (ref null $st2) (table.get $tn_struct (i32.const 0)))
    (ref.test (ref null $ar0) (table.get $tn_struct (i32.const 0)))
    (ref.test (ref null $ar1) (table.get $tn_struct (i32.const 0)))
    (ref.test (ref null $ar2) (table.get $tn_struct (i32.const 0)))
    (ref.cast (ref null $st0) (table.get $tn_struct (i32.const 0))) (drop)
    (ref.cast (ref null $st1) (table.get $tn_struct (i32.const 0))) (drop)
    (ref.cast (ref null $st2) (table.get $tn_struct (i32.const 0))) (drop)
    (ref.cast (ref null $ar0) (table.get $tn_struct (i32.const 0))) (drop)
    (ref.cast (ref null $ar1) (table.get $tn_struct (i32.const 0))) (drop)
    (ref.cast (ref null $ar2) (table.get $tn_struct (i32.const 0))) (drop)
  )

  (func (export "tn_struct2") (result i32 i32 i32 i32 i32 i32)
    (ref.test (ref null $st0) (table.get $tn_struct (i32.const 1)))
    (ref.test (ref $st0) (table.get $tn_struct (i32.const 2)))
    (ref.test (ref null $st0) (table.get $tn_struct (i32.const 3)))
    (ref.test (ref $st1) (table.get $tn_struct (i32.const 1)))
    (ref.test (ref null $st1) (table.get $tn_struct (i32.const 2)))
    (ref.test (ref $ar0) (table.get $tn_struct (i32.const 1)))
    (ref.cast (ref $st0) (table.get $tn_struct (i32.const 1))) (drop)
    (ref.cast (ref null $st0) (table.get $tn_struct (i32.const 2))) (drop)
    (ref.cast (ref $st1) (table.get $tn_struct (i32.const 2))) (drop)
    (ref.cast (ref null $st2) (table.get $tn_struct (i32.const 3))) (drop)
  )

  (func (export "tn_struct3")
    (ref.cast (ref $st0) (table.get $tn_struct (i32.const 3))) (drop)
  )

  (func (export "tn_struct4")
    (ref.cast (ref $st2) (table.get $tn_struct (i32.const 2))) (drop)
  )

  (func (export "tn_struct5") (result i32 i32 i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null $ar2) (table.get $tn_struct (i32.const 0))) (i32.const 2) (br 1))
        (drop) (i32.const 8))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null $ar2) (table.get $tn_struct (i32.const 0))) (i32.const 3) (br 1))
        (drop) (i32.const 9))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref $st0) (table.get $tn_struct (i32.const 3))) (i32.const 4) (br 1))
        (drop) (i32.const 10))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref $st0) (table.get $tn_struct (i32.const 3))) (i32.const 5) (br 1))
        (drop) (i32.const 11))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null $st1) (table.get $tn_struct (i32.const 2))) (i32.const 6) (br 1))
        (drop) (i32.const 12))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null $st1) (table.get $tn_struct (i32.const 2))) (i32.const 7) (br 1))
        (drop) (i32.const 13))
  )

  (func (export "t_array1") (result i32 i32 i32 i32 i32 i32)
    (ref.test (ref null $ar0) (table.get $t_array (i32.const 0)))
    (ref.test (ref $ar0) (table.get $t_array (i32.const 1)))
    (ref.test (ref null $ar0) (table.get $t_array (i32.const 2)))
    (ref.test (ref $ar1) (table.get $t_array (i32.const 0)))
    (ref.test (ref null $ar1) (table.get $t_array (i32.const 1)))
    (ref.test (ref $st0) (table.get $t_array (i32.const 0)))
    (ref.cast (ref $ar0) (table.get $t_array (i32.const 0))) (drop)
    (ref.cast (ref null $ar0) (table.get $t_array (i32.const 1))) (drop)
    (ref.cast (ref $ar1) (table.get $t_array (i32.const 1))) (drop)
    (ref.cast (ref null $ar2) (table.get $t_array (i32.const 2))) (drop)
  )

  (func (export "t_array2")
    (ref.cast (ref $ar0) (table.get $t_array (i32.const 2))) (drop)
  )

  (func (export "t_array3")
    (ref.cast (ref null $st0) (table.get $t_array (i32.const 0))) (drop)
  )

  (func (export "t_array4") (result i32 i32 i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null $ar0) (table.get $t_array (i32.const 0))) (i32.const 8) (br 1))
        (drop) (i32.const 14))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null $ar0) (table.get $t_array (i32.const 0))) (i32.const 9) (br 1))
        (drop) (i32.const 15))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref $ar0) (table.get $t_array (i32.const 1))) (i32.const 10) (br 1))
        (drop) (i32.const 16))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref $ar0) (table.get $t_array (i32.const 1))) (i32.const 11) (br 1))
        (drop) (i32.const 17))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null $st0) (table.get $t_array (i32.const 2))) (i32.const 12) (br 1))
        (drop) (i32.const 18))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null $st0) (table.get $t_array (i32.const 2))) (i32.const 13) (br 1))
        (drop) (i32.const 19))
  )

  (func (export "tn_array1") (result i32 i32 i32 i32 i32 i32)
    (ref.test (ref null $st0) (table.get $tn_array (i32.const 0)))
    (ref.test (ref null $st1) (table.get $tn_array (i32.const 0)))
    (ref.test (ref null $st2) (table.get $tn_array (i32.const 0)))
    (ref.test (ref null $ar0) (table.get $tn_array (i32.const 0)))
    (ref.test (ref null $ar1) (table.get $tn_array (i32.const 0)))
    (ref.test (ref null $ar2) (table.get $tn_array (i32.const 0)))
    (ref.cast (ref null $st0) (table.get $tn_array (i32.const 0))) (drop)
    (ref.cast (ref null $st1) (table.get $tn_array (i32.const 0))) (drop)
    (ref.cast (ref null $st2) (table.get $tn_array (i32.const 0))) (drop)
    (ref.cast (ref null $ar0) (table.get $tn_array (i32.const 0))) (drop)
    (ref.cast (ref null $ar1) (table.get $tn_array (i32.const 0))) (drop)
    (ref.cast (ref null $ar2) (table.get $tn_array (i32.const 0))) (drop)
  )

  (func (export "tn_array2") (result i32 i32 i32 i32 i32 i32)
    (ref.test (ref null $ar0) (table.get $tn_array (i32.const 1)))
    (ref.test (ref $ar0) (table.get $tn_array (i32.const 2)))
    (ref.test (ref null $ar0) (table.get $tn_array (i32.const 3)))
    (ref.test (ref $ar1) (table.get $tn_array (i32.const 1)))
    (ref.test (ref null $ar1) (table.get $tn_array (i32.const 2)))
    (ref.test (ref $st0) (table.get $tn_array (i32.const 1)))
    (ref.cast (ref $ar0) (table.get $tn_array (i32.const 1))) (drop)
    (ref.cast (ref null $ar0) (table.get $tn_array (i32.const 2))) (drop)
    (ref.cast (ref $ar1) (table.get $tn_array (i32.const 2))) (drop)
    (ref.cast (ref null $ar2) (table.get $tn_array (i32.const 3))) (drop)
  )

  (func (export "tn_array3")
    (ref.cast (ref $ar0) (table.get $tn_array (i32.const 3))) (drop)
  )

  (func (export "tn_array4")
    (ref.cast (ref $ar2) (table.get $tn_array (i32.const 2))) (drop)
  )

  (func (export "tn_array5") (result i32 i32 i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null $st2) (table.get $tn_array (i32.const 0))) (i32.const 7) (br 1))
        (drop) (i32.const 13))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null $st2) (table.get $tn_array (i32.const 0))) (i32.const 8) (br 1))
        (drop) (i32.const 14))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref $ar0) (table.get $tn_array (i32.const 3))) (i32.const 9) (br 1))
        (drop) (i32.const 15))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref $ar0) (table.get $tn_array (i32.const 3))) (i32.const 10) (br 1))
        (drop) (i32.const 16))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null $ar1) (table.get $tn_array (i32.const 2))) (i32.const 11) (br 1))
        (drop) (i32.const 17))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null $ar1) (table.get $tn_array (i32.const 2))) (i32.const 12) (br 1))
        (drop) (i32.const 18))
  )
)

(invoke "init")

(assert_return (invoke "t_any1") (i32.const 0) (i32.const 1) (i32.const 1) (i32.const 0) (i32.const 0))
(assert_return (invoke "t_any2") (i32.const 0) (i32.const 0) (i32.const 1) (i32.const 0) (i32.const 0))
(assert_return (invoke "t_any3") (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 1) (i32.const 0))
(assert_return (invoke "t_any4") (i32.const 0) (i32.const 0) (i32.const 1) (i32.const 1) (i32.const 0))
(assert_return (invoke "t_any5") (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 1) (i32.const 0))
(assert_return (invoke "t_any6") (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 1))
(assert_trap (invoke "t_any7") "cast failure")
(assert_trap (invoke "t_any8") "cast failure")
(assert_return (invoke "t_any9") (i32.const 6) (i32.const 7) (i32.const 12) (i32.const 9))

(assert_return (invoke "tn_any1") (i32.const 1) (i32.const 1) (i32.const 1) (i32.const 1) (i32.const 1) (i32.const 1))
(assert_return (invoke "tn_any2") (i32.const 0) (i32.const 0) (i32.const 1) (i32.const 0) (i32.const 1))
(assert_trap (invoke "tn_any3") "cast failure")
(assert_trap (invoke "tn_any4") "cast failure")
(assert_trap (invoke "tn_any5") "cast failure")
(assert_return (invoke "tn_any6") (i32.const 2) (i32.const 9) (i32.const 10) (i32.const 5) (i32.const 6) (i32.const 13))
(assert_return (invoke "tn_any7") (i32.const 15) (i32.const 10) (i32.const 17) (i32.const 12) (i32.const 13) (i32.const 20))

(assert_return (invoke "t_struct1") (i32.const 1) (i32.const 1) (i32.const 0) (i32.const 0) (i32.const 1) (i32.const 0))
(assert_trap (invoke "t_struct2") "cast failure")
(assert_trap (invoke "t_struct3") "cast failure")
(assert_return (invoke "t_struct4") (i32.const 12) (i32.const 7) (i32.const 14) (i32.const 9) (i32.const 10) (i32.const 17))

(assert_return (invoke "tn_struct1") (i32.const 1) (i32.const 1) (i32.const 1) (i32.const 1) (i32.const 1) (i32.const 1))
(assert_return (invoke "tn_struct2") (i32.const 1) (i32.const 1) (i32.const 0) (i32.const 0) (i32.const 1) (i32.const 0))
(assert_trap (invoke "tn_struct3") "cast failure")
(assert_trap (invoke "tn_struct4") "cast failure")
(assert_return (invoke "tn_struct5") (i32.const 8) (i32.const 3) (i32.const 4) (i32.const 11) (i32.const 12) (i32.const 7))

(assert_return (invoke "t_array1") (i32.const 1) (i32.const 1) (i32.const 0) (i32.const 0) (i32.const 1) (i32.const 0))
(assert_trap (invoke "t_array2") "cast failure")
(assert_trap (invoke "t_array3") "cast failure")
(assert_return (invoke "t_array4") (i32.const 14) (i32.const 9) (i32.const 16) (i32.const 11) (i32.const 12) (i32.const 19))

(assert_return (invoke "tn_array1") (i32.const 1) (i32.const 1) (i32.const 1) (i32.const 1) (i32.const 1) (i32.const 1))
(assert_return (invoke "tn_array2") (i32.const 1) (i32.const 1) (i32.const 0) (i32.const 0) (i32.const 1) (i32.const 0))
(assert_trap (invoke "tn_array3") "cast failure")
(assert_trap (invoke "tn_array4") "cast failure")
(assert_return (invoke "tn_array5") (i32.const 13) (i32.const 8) (i32.const 9) (i32.const 16) (i32.const 17) (i32.const 12))
