(module
  (type $st0 (struct (field i32)))
  (type $st1 (struct (field i64)))
  (type $ar0 (array i32))
  (type $ar1 (array i64))

  (table $t_any 3 (ref any) (ref.i31 (i32.const 0)))
  (table $tn_any 4 (ref null any))
  (table $t_struct 2 (ref struct) (struct.new_default $st0))
  (table $tn_struct 3 (ref null struct))
  (table $t_array 2 (ref array) (array.new_default $ar0 (i32.const 1)))
  (table $tn_array 3 (ref null array))

  (func (export "init")
    (table.set $t_any (i32.const 0) (ref.i31 (i32.const 1)))
    (table.set $t_any (i32.const 1) (struct.new_default $st0))
    (table.set $t_any (i32.const 2) (array.new_default $ar0 (i32.const 1)))

    (table.set $tn_any (i32.const 0) (ref.null any))
    (table.set $tn_any (i32.const 1) (ref.i31 (i32.const 1)))
    (table.set $tn_any (i32.const 2) (struct.new_default $st0))
    (table.set $tn_any (i32.const 3) (array.new_default $ar0 (i32.const 1)))

    ;; $t_struct[0] is (struct.new_default $st0)
    (table.set $t_struct (i32.const 1) (struct.new_default $st1))

    ;; $tn_struct[0] is ref.null
    (table.set $tn_struct (i32.const 1) (struct.new_default $st0))
    (table.set $tn_struct (i32.const 2) (struct.new_default $st1))

    ;; $t_array[0] is (array.new_default $ar0 (i32.const 1))
    (table.set $t_array (i32.const 1) (array.new_default $ar1 (i32.const 1)))

    ;; $tn_array[0] is ref.null
    (table.set $tn_array (i32.const 1) (array.new_default $ar0 (i32.const 1)))
    (table.set $tn_array (i32.const 2) (array.new_default $ar1 (i32.const 1)))
  )

  (func (export "t_any1") (result i32 i32)
    (ref.test (ref i31) (table.get $t_any (i32.const 0)))
    (ref.test (ref i31) (table.get $t_any (i32.const 1)))
  )

  (func (export "t_any2") (result i32 i32)
    (ref.test (ref struct) (table.get $t_any (i32.const 1)))
    (ref.test (ref struct) (table.get $t_any (i32.const 0)))
    (ref.cast (ref struct) (table.get $t_any (i32.const 1))) (drop)
  )

  (func (export "t_any3") (result i32 i32)
    (ref.test (ref array) (table.get $t_any (i32.const 2)))
    (ref.test (ref array) (table.get $t_any (i32.const 0)))
    (ref.cast (ref array) (table.get $t_any (i32.const 2))) (drop)
  )

  (func (export "t_any4")
    (ref.cast (ref i31) (table.get $t_any (i32.const 1))) (drop)
  )

  (func (export "t_any5")
    (ref.cast (ref struct) (table.get $t_any (i32.const 0))) (drop)
  )

  (func (export "t_any6")
    (ref.cast (ref array) (table.get $t_any (i32.const 1))) (drop)
  )

  (func (export "t_any7") (result i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref i31) (table.get $t_any (i32.const 0))) (i32.const 3) (br 1))
        (drop) (i32.const 7))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref i31) (table.get $t_any (i32.const 0))) (i32.const 4) (br 1))
        (drop) (i32.const 8))
  )

  (func (export "t_any8") (result i32 i32 i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref struct) (table.get $t_any (i32.const 0))) (i32.const 6) (br 1))
        (drop) (i32.const 12))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref struct) (table.get $t_any (i32.const 0))) (i32.const 7) (br 1))
        (drop) (i32.const 13))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref struct) (table.get $t_any (i32.const 1))) (i32.const 8) (br 1))
        (drop) (i32.const 14))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref struct) (table.get $t_any (i32.const 1))) (i32.const 9) (br 1))
        (drop) (i32.const 15))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref struct) (table.get $t_any (i32.const 2))) (i32.const 10) (br 1))
        (drop) (i32.const 16))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref struct) (table.get $t_any (i32.const 2))) (i32.const 11) (br 1))
        (drop) (i32.const 17))
  )

  (func (export "t_any9") (result i32 i32 i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref array) (table.get $t_any (i32.const 0))) (i32.const 2) (br 1))
        (drop) (i32.const 8))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref array) (table.get $t_any (i32.const 0))) (i32.const 3) (br 1))
        (drop) (i32.const 9))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref array) (table.get $t_any (i32.const 1))) (i32.const 4) (br 1))
        (drop) (i32.const 10))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref array) (table.get $t_any (i32.const 1))) (i32.const 5) (br 1))
        (drop) (i32.const 11))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref array) (table.get $t_any (i32.const 2))) (i32.const 6) (br 1))
        (drop) (i32.const 12))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref array) (table.get $t_any (i32.const 2))) (i32.const 7) (br 1))
        (drop) (i32.const 13))
  )

  (func (export "tn_any1") (result i32 i32 i32 i32)
    (ref.test (ref i31) (table.get $tn_any (i32.const 0)))
    (ref.test (ref null i31) (table.get $tn_any (i32.const 0)))
    (ref.test (ref i31) (table.get $tn_any (i32.const 1)))
    (ref.test (ref null i31) (table.get $tn_any (i32.const 1)))
  )

  (func (export "tn_any2") (result i32 i32 i32 i32)
    (ref.test (ref struct) (table.get $tn_any (i32.const 0)))
    (ref.test (ref null struct) (table.get $tn_any (i32.const 0)))
    (ref.test (ref struct) (table.get $tn_any (i32.const 2)))
    (ref.test (ref null struct) (table.get $tn_any (i32.const 2)))
    (ref.cast (ref null struct) (table.get $tn_any (i32.const 0))) (drop)
    (ref.cast (ref struct) (table.get $tn_any (i32.const 2))) (drop)
  )

  (func (export "tn_any3") (result i32 i32 i32 i32)
    (ref.test (ref array) (table.get $tn_any (i32.const 0)))
    (ref.test (ref null array) (table.get $tn_any (i32.const 0)))
    (ref.test (ref array) (table.get $tn_any (i32.const 3)))
    (ref.test (ref null array) (table.get $tn_any (i32.const 3)))
    (ref.cast (ref null array) (table.get $tn_any (i32.const 0))) (drop)
    (ref.cast (ref array) (table.get $tn_any (i32.const 3))) (drop)
  )

  (func (export "tn_any4")
    (ref.cast (ref i31) (table.get $tn_any (i32.const 0))) (drop)
  )

  (func (export "tn_any5")
    (ref.cast (ref null i31) (table.get $tn_any (i32.const 2))) (drop)
  )

  (func (export "tn_any6")
    (ref.cast (ref struct) (table.get $tn_any (i32.const 0))) (drop)
  )

  (func (export "tn_any7")
    (ref.cast (ref null struct) (table.get $tn_any (i32.const 1))) (drop)
  )

  (func (export "tn_any8")
    (ref.cast (ref array) (table.get $tn_any (i32.const 0))) (drop)
  )

  (func (export "tn_any9")
    (ref.cast (ref null array) (table.get $tn_any (i32.const 2))) (drop)
  )

  (func (export "tn_any10") (result i32 i32 i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref i31) (table.get $tn_any (i32.const 0))) (i32.const 5) (br 1))
        (drop) (i32.const 11))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref i31) (table.get $tn_any (i32.const 0))) (i32.const 6) (br 1))
        (drop) (i32.const 12))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref i31) (table.get $tn_any (i32.const 1))) (i32.const 7) (br 1))
        (drop) (i32.const 13))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref i31) (table.get $tn_any (i32.const 1))) (i32.const 8) (br 1))
        (drop) (i32.const 14))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref i31) (table.get $tn_any (i32.const 2))) (i32.const 9) (br 1))
        (drop) (i32.const 15))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref i31) (table.get $tn_any (i32.const 2))) (i32.const 10) (br 1))
        (drop) (i32.const 16))
  )

  (func (export "tn_any11") (result i32 i32 i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null i31) (table.get $tn_any (i32.const 0))) (i32.const 8) (br 1))
        (drop) (i32.const 14))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null i31) (table.get $tn_any (i32.const 0))) (i32.const 9) (br 1))
        (drop) (i32.const 15))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null i31) (table.get $tn_any (i32.const 1))) (i32.const 10) (br 1))
        (drop) (i32.const 16))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null i31) (table.get $tn_any (i32.const 1))) (i32.const 11) (br 1))
        (drop) (i32.const 17))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null i31) (table.get $tn_any (i32.const 2))) (i32.const 12) (br 1))
        (drop) (i32.const 18))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null i31) (table.get $tn_any (i32.const 2))) (i32.const 13) (br 1))
        (drop) (i32.const 19))
  )

  (func (export "tn_any12") (result i32 i32 i32 i32 i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref struct) (table.get $tn_any (i32.const 0))) (i32.const 2) (br 1))
        (drop) (i32.const 10))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref struct) (table.get $tn_any (i32.const 0))) (i32.const 3) (br 1))
        (drop) (i32.const 11))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref struct) (table.get $tn_any (i32.const 1))) (i32.const 4) (br 1))
        (drop) (i32.const 12))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref struct) (table.get $tn_any (i32.const 1))) (i32.const 5) (br 1))
        (drop) (i32.const 13))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref struct) (table.get $tn_any (i32.const 2))) (i32.const 6) (br 1))
        (drop) (i32.const 14))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref struct) (table.get $tn_any (i32.const 2))) (i32.const 7) (br 1))
        (drop) (i32.const 15))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref struct) (table.get $tn_any (i32.const 3))) (i32.const 8) (br 1))
        (drop) (i32.const 16))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref struct) (table.get $tn_any (i32.const 3))) (i32.const 9) (br 1))
        (drop) (i32.const 17))
  )

  (func (export "tn_any13") (result i32 i32 i32 i32 i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null struct) (table.get $tn_any (i32.const 0))) (i32.const 7) (br 1))
        (drop) (i32.const 15))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null struct) (table.get $tn_any (i32.const 0))) (i32.const 8) (br 1))
        (drop) (i32.const 16))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null struct) (table.get $tn_any (i32.const 1))) (i32.const 9) (br 1))
        (drop) (i32.const 17))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null struct) (table.get $tn_any (i32.const 1))) (i32.const 10) (br 1))
        (drop) (i32.const 18))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null struct) (table.get $tn_any (i32.const 2))) (i32.const 11) (br 1))
        (drop) (i32.const 19))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null struct) (table.get $tn_any (i32.const 2))) (i32.const 12) (br 1))
        (drop) (i32.const 20))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null struct) (table.get $tn_any (i32.const 3))) (i32.const 13) (br 1))
        (drop) (i32.const 21))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null struct) (table.get $tn_any (i32.const 3))) (i32.const 14) (br 1))
        (drop) (i32.const 22))
  )

  (func (export "tn_any14") (result i32 i32 i32 i32 i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref array) (table.get $tn_any (i32.const 0))) (i32.const 10) (br 1))
        (drop) (i32.const 18))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref array) (table.get $tn_any (i32.const 0))) (i32.const 11) (br 1))
        (drop) (i32.const 19))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref array) (table.get $tn_any (i32.const 1))) (i32.const 12) (br 1))
        (drop) (i32.const 20))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref array) (table.get $tn_any (i32.const 1))) (i32.const 13) (br 1))
        (drop) (i32.const 21))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref array) (table.get $tn_any (i32.const 2))) (i32.const 14) (br 1))
        (drop) (i32.const 22))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref array) (table.get $tn_any (i32.const 2))) (i32.const 15) (br 1))
        (drop) (i32.const 23))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref array) (table.get $tn_any (i32.const 3))) (i32.const 16) (br 1))
        (drop) (i32.const 24))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref array) (table.get $tn_any (i32.const 3))) (i32.const 17) (br 1))
        (drop) (i32.const 25))
  )

  (func (export "tn_any15") (result i32 i32 i32 i32 i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null array) (table.get $tn_any (i32.const 0))) (i32.const 3) (br 1))
        (drop) (i32.const 11))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null array) (table.get $tn_any (i32.const 0))) (i32.const 4) (br 1))
        (drop) (i32.const 12))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null array) (table.get $tn_any (i32.const 1))) (i32.const 5) (br 1))
        (drop) (i32.const 13))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null array) (table.get $tn_any (i32.const 1))) (i32.const 6) (br 1))
        (drop) (i32.const 14))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null array) (table.get $tn_any (i32.const 2))) (i32.const 7) (br 1))
        (drop) (i32.const 15))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null array) (table.get $tn_any (i32.const 2))) (i32.const 8) (br 1))
        (drop) (i32.const 16))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null array) (table.get $tn_any (i32.const 3))) (i32.const 9) (br 1))
        (drop) (i32.const 17))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null array) (table.get $tn_any (i32.const 3))) (i32.const 10) (br 1))
        (drop) (i32.const 18))
  )

  (func (export "t_struct1") (result i32 i32)
    (ref.test (ref struct) (table.get $t_struct (i32.const 0)))
    (ref.test (ref array) (table.get $t_struct (i32.const 1)))
    (ref.cast (ref struct) (table.get $t_struct (i32.const 0))) (drop)
  )

  (func (export "t_struct2")
    (ref.cast (ref array) (table.get $t_struct (i32.const 1))) (drop)
  )

  (func (export "t_struct3") (result i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref struct) (table.get $t_struct (i32.const 0))) (i32.const 9) (br 1))
        (drop) (i32.const 13))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref struct) (table.get $t_struct (i32.const 0))) (i32.const 10) (br 1))
        (drop) (i32.const 14))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref array) (table.get $t_struct (i32.const 1))) (i32.const 11) (br 1))
        (drop) (i32.const 15))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref array) (table.get $t_struct (i32.const 1))) (i32.const 12) (br 1))
        (drop) (i32.const 16))
  )

  (func (export "tn_struct1") (result i32 i32 i32)
    (ref.test (ref struct) (table.get $tn_struct (i32.const 0)))
    (ref.test (ref struct) (table.get $tn_struct (i32.const 1)))
    (ref.test (ref array) (table.get $tn_struct (i32.const 2)))
    (ref.cast (ref struct) (table.get $tn_struct (i32.const 2))) (drop)
  )

  (func (export "tn_struct2") (result i32 i32 i32 i32)
    (ref.test (ref null struct) (table.get $tn_struct (i32.const 0)))
    (ref.test (ref null struct) (table.get $tn_struct (i32.const 1)))
    (ref.test (ref null array) (table.get $tn_struct (i32.const 0)))
    (ref.test (ref null array) (table.get $tn_struct (i32.const 2)))
    (ref.cast (ref null struct) (table.get $tn_struct (i32.const 0))) (drop)
    (ref.cast (ref null struct) (table.get $tn_struct (i32.const 2))) (drop)
  )

  (func (export "tn_struct3")
    (ref.cast (ref array) (table.get $tn_struct (i32.const 0))) (drop)
  )

  (func (export "tn_struct4")
    (ref.cast (ref null array) (table.get $tn_struct (i32.const 1))) (drop)
  )

  (func (export "tn_struct5") (result i32 i32 i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref struct) (table.get $tn_struct (i32.const 0))) (i32.const 5) (br 1))
        (drop) (i32.const 11))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref struct) (table.get $tn_struct (i32.const 0))) (i32.const 6) (br 1))
        (drop) (i32.const 12))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref struct) (table.get $tn_struct (i32.const 1))) (i32.const 7) (br 1))
        (drop) (i32.const 13))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref struct) (table.get $tn_struct (i32.const 1))) (i32.const 8) (br 1))
        (drop) (i32.const 14))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref array) (table.get $tn_struct (i32.const 2))) (i32.const 9) (br 1))
        (drop) (i32.const 15))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref array) (table.get $tn_struct (i32.const 2))) (i32.const 10) (br 1))
        (drop) (i32.const 16))
  )

  (func (export "tn_struct6") (result i32 i32 i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null struct) (table.get $tn_struct (i32.const 0))) (i32.const 11) (br 1))
        (drop) (i32.const 17))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null struct) (table.get $tn_struct (i32.const 0))) (i32.const 12) (br 1))
        (drop) (i32.const 18))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null struct) (table.get $tn_struct (i32.const 1))) (i32.const 13) (br 1))
        (drop) (i32.const 19))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null struct) (table.get $tn_struct (i32.const 1))) (i32.const 14) (br 1))
        (drop) (i32.const 20))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null array) (table.get $tn_struct (i32.const 2))) (i32.const 15) (br 1))
        (drop) (i32.const 21))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null array) (table.get $tn_struct (i32.const 2))) (i32.const 16) (br 1))
        (drop) (i32.const 22))
  )

  (func (export "t_array1") (result i32 i32)
    (ref.test (ref array) (table.get $t_array (i32.const 0)))
    (ref.test (ref struct) (table.get $t_array (i32.const 1)))
    (ref.cast (ref array) (table.get $t_array (i32.const 0))) (drop)
  )

  (func (export "t_array2")
    (ref.cast (ref struct) (table.get $t_array (i32.const 1))) (drop)
  )

  (func (export "t_array3") (result i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref array) (table.get $t_array (i32.const 0))) (i32.const 1) (br 1))
        (drop) (i32.const 5))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref array) (table.get $t_array (i32.const 0))) (i32.const 2) (br 1))
        (drop) (i32.const 6))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref struct) (table.get $t_array (i32.const 1))) (i32.const 3) (br 1))
        (drop) (i32.const 7))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref struct) (table.get $t_array (i32.const 1))) (i32.const 4) (br 1))
        (drop) (i32.const 8))
  )

  (func (export "tn_array1") (result i32 i32 i32)
    (ref.test (ref array) (table.get $tn_array (i32.const 0)))
    (ref.test (ref array) (table.get $tn_array (i32.const 1)))
    (ref.test (ref struct) (table.get $tn_array (i32.const 2)))
    (ref.cast (ref array) (table.get $tn_array (i32.const 2))) (drop)
  )

  (func (export "tn_array2") (result i32 i32 i32 i32)
    (ref.test (ref null array) (table.get $tn_array (i32.const 0)))
    (ref.test (ref null array) (table.get $tn_array (i32.const 1)))
    (ref.test (ref null struct) (table.get $tn_array (i32.const 0)))
    (ref.test (ref null struct) (table.get $tn_array (i32.const 2)))
    (ref.cast (ref null array) (table.get $tn_array (i32.const 0))) (drop)
    (ref.cast (ref null array) (table.get $tn_array (i32.const 2))) (drop)
  )

  (func (export "tn_array3")
    (ref.cast (ref struct) (table.get $tn_array (i32.const 0))) (drop)
  )

  (func (export "tn_array4")
    (ref.cast (ref null struct) (table.get $tn_array (i32.const 1))) (drop)
  )

  (func (export "tn_array5") (result i32 i32 i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref array) (table.get $tn_array (i32.const 0))) (i32.const 8) (br 1))
        (drop) (i32.const 14))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref array) (table.get $tn_array (i32.const 0))) (i32.const 9) (br 1))
        (drop) (i32.const 15))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref array) (table.get $tn_array (i32.const 1))) (i32.const 10) (br 1))
        (drop) (i32.const 16))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref array) (table.get $tn_array (i32.const 1))) (i32.const 11) (br 1))
        (drop) (i32.const 17))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref struct) (table.get $tn_array (i32.const 2))) (i32.const 12) (br 1))
        (drop) (i32.const 18))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref struct) (table.get $tn_array (i32.const 2))) (i32.const 13) (br 1))
        (drop) (i32.const 19))
  )

  (func (export "tn_array6") (result i32 i32 i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null array) (table.get $tn_array (i32.const 0))) (i32.const 4) (br 1))
        (drop) (i32.const 10))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null array) (table.get $tn_array (i32.const 0))) (i32.const 5) (br 1))
        (drop) (i32.const 11))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null array) (table.get $tn_array (i32.const 1))) (i32.const 6) (br 1))
        (drop) (i32.const 12))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null array) (table.get $tn_array (i32.const 1))) (i32.const 7) (br 1))
        (drop) (i32.const 13))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null struct) (table.get $tn_array (i32.const 2))) (i32.const 8) (br 1))
        (drop) (i32.const 14))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null struct) (table.get $tn_array (i32.const 2))) (i32.const 9) (br 1))
        (drop) (i32.const 15))
  )

  (func (export "ref_any1") (result i32 i32 i32)
    (ref.test (ref any) (table.get $t_any (i32.const 0)))
    (ref.test (ref any) (table.get $t_struct (i32.const 0)))
    (ref.test (ref any) (table.get $t_array (i32.const 0)))
    (ref.cast (ref any) (table.get $t_any (i32.const 1))) (drop)
    (ref.cast (ref any) (table.get $t_struct (i32.const 1))) (drop)
    (ref.cast (ref any) (table.get $t_array (i32.const 1))) (drop)
  )

  (func (export "ref_any2") (result i32 i32 i32 i32)
    (ref.test (ref any) (table.get $tn_any (i32.const 0)))
    (ref.test (ref any) (table.get $tn_any (i32.const 1)))
    (ref.test (ref any) (table.get $tn_struct (i32.const 0)))
    (ref.test (ref any) (table.get $tn_array (i32.const 1)))
    (ref.cast (ref any) (table.get $tn_any (i32.const 1))) (drop)
    (ref.cast (ref any) (table.get $tn_struct (i32.const 1))) (drop)
    (ref.cast (ref any) (table.get $tn_array (i32.const 1))) (drop)
  )

  (func (export "ref_any3")
    (ref.cast (ref any) (table.get $tn_any (i32.const 0))) (drop)
  )

  (func (export "ref_any4")
    (ref.cast (ref any) (table.get $tn_array (i32.const 0))) (drop)
  )

  (func (export "ref_any5") (result i32 i32 i32)
    (ref.test (ref null any) (table.get $tn_any (i32.const 0)))
    (ref.test (ref null any) (table.get $tn_struct (i32.const 0)))
    (ref.test (ref null any) (table.get $tn_array (i32.const 0)))
    (ref.cast (ref null any) (table.get $tn_any (i32.const 1))) (drop)
    (ref.cast (ref null any) (table.get $tn_struct (i32.const 1))) (drop)
    (ref.cast (ref null any) (table.get $tn_array (i32.const 1))) (drop)
  )

  (func (export "ref_any6") (result i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref any) (table.get $tn_any (i32.const 0))) (i32.const 6) (br 1))
        (drop) (i32.const 10))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref any) (table.get $tn_struct (i32.const 0))) (i32.const 7) (br 1))
        (drop) (i32.const 11))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref any) (table.get $tn_any (i32.const 1))) (i32.const 8) (br 1))
        (drop) (i32.const 12))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref any) (table.get $tn_array (i32.const 1))) (i32.const 9) (br 1))
        (drop) (i32.const 13))
  )

  (func (export "ref_any7") (result i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null any) (table.get $tn_any (i32.const 0))) (i32.const 11) (br 1))
        (drop) (i32.const 15))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null any) (table.get $tn_struct (i32.const 0))) (i32.const 12) (br 1))
        (drop) (i32.const 16))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null any) (table.get $tn_any (i32.const 1))) (i32.const 13) (br 1))
        (drop) (i32.const 17))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null any) (table.get $tn_array (i32.const 1))) (i32.const 14) (br 1))
        (drop) (i32.const 18))
  )

  (func (export "ref_none1") (result i32 i32 i32)
    (ref.test (ref none) (table.get $t_any (i32.const 0)))
    (ref.test (ref none) (table.get $t_struct (i32.const 0)))
    (ref.test (ref none) (table.get $t_array (i32.const 0)))
  )

  (func (export "ref_none2") (result i32 i32 i32 i32)
    (ref.test (ref none) (table.get $tn_any (i32.const 0)))
    (ref.test (ref none) (table.get $tn_any (i32.const 1)))
    (ref.test (ref none) (table.get $tn_struct (i32.const 0)))
    (ref.test (ref none) (table.get $tn_array (i32.const 1)))
  )

  (func (export "ref_none3")
    (ref.cast (ref none) (table.get $tn_any (i32.const 0))) (drop)
  )

  (func (export "ref_none4")
    (ref.cast (ref null none) (table.get $tn_any (i32.const 1))) (drop)
  )

  (func (export "ref_none5")
    (ref.cast (ref none) (table.get $tn_struct (i32.const 0))) (drop)
  )

  (func (export "ref_none6") (result i32 i32 i32 i32)
    (ref.test (ref null none) (table.get $tn_any (i32.const 0)))
    (ref.test (ref null none) (table.get $tn_any (i32.const 1)))
    (ref.test (ref null none) (table.get $tn_struct (i32.const 0)))
    (ref.test (ref null none) (table.get $tn_array (i32.const 1)))
    (ref.cast (ref null none) (table.get $tn_any (i32.const 0))) (drop)
    (ref.cast (ref null none) (table.get $tn_struct (i32.const 0))) (drop)
    (ref.cast (ref null none) (table.get $tn_array (i32.const 0))) (drop)
  )

  (func (export "ref_none7") (result i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref none) (table.get $tn_any (i32.const 0))) (i32.const 3) (br 1))
        (drop) (i32.const 7))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref none) (table.get $tn_struct (i32.const 0))) (i32.const 4) (br 1))
        (drop) (i32.const 8))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref none) (table.get $tn_any (i32.const 1))) (i32.const 5) (br 1))
        (drop) (i32.const 9))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref none) (table.get $tn_array (i32.const 1))) (i32.const 6) (br 1))
        (drop) (i32.const 10))
  )

  (func (export "ref_none8") (result i32 i32 i32 i32)
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null none) (table.get $tn_any (i32.const 0))) (i32.const 7) (br 1))
        (drop) (i32.const 11))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null none) (table.get $tn_struct (i32.const 0))) (i32.const 8) (br 1))
        (drop) (i32.const 12))
     (block (result i32)
        (block (result anyref) (br_on_cast 0 anyref (ref null none) (table.get $tn_any (i32.const 1))) (i32.const 9) (br 1))
        (drop) (i32.const 13))
     (block (result i32)
        (block (result anyref) (br_on_cast_fail 0 anyref (ref null none) (table.get $tn_array (i32.const 1))) (i32.const 10) (br 1))
        (drop) (i32.const 14))
  )
)

(invoke "init")

(assert_return (invoke "t_any1") (i32.const 1) (i32.const 0))
(assert_return (invoke "t_any2") (i32.const 1) (i32.const 0))
(assert_return (invoke "t_any3") (i32.const 1) (i32.const 0))
(assert_trap (invoke "t_any4") "cast failure")
(assert_trap (invoke "t_any5") "cast failure")
(assert_trap (invoke "t_any6") "cast failure")
(assert_return (invoke "t_any7") (i32.const 7) (i32.const 4))
(assert_return (invoke "t_any8") (i32.const 6) (i32.const 13) (i32.const 14) (i32.const 9) (i32.const 10) (i32.const 17))
(assert_return (invoke "t_any9") (i32.const 2) (i32.const 9) (i32.const 4) (i32.const 11) (i32.const 12) (i32.const 7))

(assert_return (invoke "tn_any1") (i32.const 0) (i32.const 1) (i32.const 1) (i32.const 1))
(assert_return (invoke "tn_any2") (i32.const 0) (i32.const 1) (i32.const 1) (i32.const 1))
(assert_return (invoke "tn_any3") (i32.const 0) (i32.const 1) (i32.const 1) (i32.const 1))
(assert_trap (invoke "tn_any4") "cast failure")
(assert_trap (invoke "tn_any5") "cast failure")
(assert_trap (invoke "tn_any6") "cast failure")
(assert_trap (invoke "tn_any7") "cast failure")
(assert_trap (invoke "tn_any8") "cast failure")
(assert_trap (invoke "tn_any9") "cast failure")
(assert_return (invoke "tn_any10") (i32.const 5) (i32.const 12) (i32.const 13) (i32.const 8) (i32.const 9) (i32.const 16))
(assert_return (invoke "tn_any11") (i32.const 14) (i32.const 9) (i32.const 16) (i32.const 11) (i32.const 12) (i32.const 19))
(assert_return (invoke "tn_any12") (i32.const 2) (i32.const 11) (i32.const 4) (i32.const 13) (i32.const 14) (i32.const 7) (i32.const 8) (i32.const 17))
(assert_return (invoke "tn_any13") (i32.const 15) (i32.const 8) (i32.const 9) (i32.const 18) (i32.const 19) (i32.const 12) (i32.const 13) (i32.const 22))
(assert_return (invoke "tn_any14") (i32.const 10) (i32.const 19) (i32.const 12) (i32.const 21) (i32.const 14) (i32.const 23) (i32.const 24) (i32.const 17))
(assert_return (invoke "tn_any15") (i32.const 11) (i32.const 4) (i32.const 5) (i32.const 14) (i32.const 7) (i32.const 16) (i32.const 17) (i32.const 10))

(assert_return (invoke "t_struct1") (i32.const 1) (i32.const 0))
(assert_trap (invoke "t_struct2") "cast failure")
(assert_return (invoke "t_struct3") (i32.const 13) (i32.const 10) (i32.const 11) (i32.const 16))

(assert_return (invoke "tn_struct1") (i32.const 0) (i32.const 1) (i32.const 0))
(assert_return (invoke "tn_struct2") (i32.const 1) (i32.const 1) (i32.const 1) (i32.const 0))
(assert_trap (invoke "tn_struct3") "cast failure")
(assert_trap (invoke "tn_struct4") "cast failure")
(assert_return (invoke "tn_struct5") (i32.const 5) (i32.const 12) (i32.const 13) (i32.const 8) (i32.const 9) (i32.const 16))
(assert_return (invoke "tn_struct6") (i32.const 17) (i32.const 12) (i32.const 19) (i32.const 14) (i32.const 15) (i32.const 22))

(assert_return (invoke "t_array1") (i32.const 1) (i32.const 0))
(assert_trap (invoke "t_array2") "cast failure")
(assert_return (invoke "t_array3") (i32.const 5) (i32.const 2) (i32.const 3) (i32.const 8))

(assert_return (invoke "tn_array1") (i32.const 0) (i32.const 1) (i32.const 0))
(assert_return (invoke "tn_array2") (i32.const 1) (i32.const 1) (i32.const 1) (i32.const 0))
(assert_trap (invoke "tn_array3") "cast failure")
(assert_trap (invoke "tn_array4") "cast failure")
(assert_return (invoke "tn_array5") (i32.const 8) (i32.const 15) (i32.const 16) (i32.const 11) (i32.const 12) (i32.const 19))
(assert_return (invoke "tn_array6") (i32.const 10) (i32.const 5) (i32.const 12) (i32.const 7) (i32.const 8) (i32.const 15))

(assert_return (invoke "ref_any1") (i32.const 1) (i32.const 1) (i32.const 1))
(assert_return (invoke "ref_any2") (i32.const 0) (i32.const 1) (i32.const 0) (i32.const 1))
(assert_trap (invoke "ref_any3") "cast failure")
(assert_trap (invoke "ref_any4") "cast failure")
(assert_return (invoke "ref_any5") (i32.const 1) (i32.const 1) (i32.const 1))
(assert_return (invoke "ref_any6") (i32.const 6) (i32.const 11) (i32.const 12) (i32.const 9))
(assert_return (invoke "ref_any7") (i32.const 15) (i32.const 12) (i32.const 17) (i32.const 14))

(assert_return (invoke "ref_none1") (i32.const 0) (i32.const 0) (i32.const 0))
(assert_return (invoke "ref_none2") (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0))
(assert_trap (invoke "ref_none3") "cast failure")
(assert_trap (invoke "ref_none4") "cast failure")
(assert_trap (invoke "ref_none5") "cast failure")
(assert_return (invoke "ref_none6") (i32.const 1) (i32.const 0) (i32.const 1) (i32.const 0))
(assert_return (invoke "ref_none7") (i32.const 3) (i32.const 8) (i32.const 5) (i32.const 10))
(assert_return (invoke "ref_none8") (i32.const 11) (i32.const 8) (i32.const 9) (i32.const 14))
